- name: Directories are present
  file:
    dest: "{{ item }}"
    state: directory
    owner: vagrant
  with_items: "{{ directories }}"
  tags: [gitea]

- name: Container is running
  docker_container:
    image: gitea/gitea:latest
    name: gitea
    state: started
    restart_policy: always
    env:
      USER_UID: 1000
      USER_GID: 1000
    ports: "{{ ports }}"
    volumes: "{{ volumes }}"
  tags: [gitea]
