ports:
  - '443:443'

directories:
  - /data/nginx/conf.d
  - /data/nginx/includes
  - /data/nginx/logs
  - /data/nginx/upstreams
  - /data/nginx/templates

files: [
  {src: 'services.conf', dest: '/data/nginx/conf.d/services.conf'},
  {src: 'nginx-includes.conf', dest: '/data/nginx/includes/nginx-includes.conf'}
]

volumes:
  - /data/nginx/conf.d:/etc/nginx/conf.d
  - /data/nginx/includes:/etc/nginx/includes
  - /data/nginx/upstreams:/etc/nginx/upstreams
  - /vagrant/ssl/nginx-selfsigned.crt:/etc/ssl/nginx-selfsigned.crt
  - /vagrant/ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
  - /vagrant/ssl/dhparam.pem:/etc/ssl/dhparam.pem
