docker_extra: ""

centos_files: [
  { src: "docker.centos.repo", dest: "/etc/yum.repos.d/docker.repo" },
  { src: "docker.centos.service", dest: "/lib/systemd/system/docker.service" },
  { src: "docker.centos.socket", dest: "/usr/lib/systemd/system/docker.socket" },
]

# WORKAROUND: creating docker.centos.socket,  try newer version of docker