- name: CentOS files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ centos_files }}"
  tags: [docker]

- name: CentOS package is installed
  yum:
    name: docker-engine
    state: present
  tags: [docker]

- name: CentOS Daemon is reloaded
  command: systemctl daemon-reload
  tags: [docker]

- name: CentOS service is running
  service:
    name: docker
    state: started
  tags: [docker]

- name: python-pip is installed
  yum:
    name: python-pip
    state: present
  tags: [docker]

- name: docker-py is installed
  pip:
    name: docker-py
    version: "{{ docker_py_version }}"
    state: present
  tags: [docker]
